const mongoose = require('mongoose');
const VehicleModel = require('../models/VehicleModel');

// Connect to MongoDB
mongoose.connect('mongodb://win:KZSkFl1aamuVfNb9@ac-evylqtx-shard-00-00.xhngg04.mongodb.net:27017,ac-evylqtx-shard-00-01.xhngg04.mongodb.net:27017,ac-evylqtx-shard-00-02.xhngg04.mongodb.net:27017/?ssl=true&replicaSet=atlas-12fnql-shard-0&authSource=admin&retryWrites=true&w=majority&appName=autorizz-db', {
  useNewUrlParser: true,
  useUnifiedTopology: true,
  useFindAndModify: false
});

const sampleVehicles = [
  {
    title: 'BMW 3 Series 320d',
    description: 'Efficient diesel engine with excellent fuel economy',
    price: 25000,
    imagePath: 'https://m-qa.atcdn.co.uk/a/media/800x600/42f1d89a24cc473f875e809fa0db990e.jpg',
    year: 2020,
    brand: 'BMW',
    model: '3 Series',
    fuelType: 'Diesel',
    autotraderId: 'bmw_3_series_001',
    category: 'cars',
    bodyType: 'Saloon',
    mileage: 25000,
    transmission: 'Manual',
    doors: 4,
    seats: 5,
    co2Emissions: 120,
    engineSize: '2.0',
    power: '190',
    topSpeed: 140,
    acceleration: 7.2,
    mpg: 55,
    tax: 150,
    insurance: 'Group 20',
    drivetrain: 'RWD',
    cylinders: 4,
    colour: 'Black',
    previousOwners: 1,
    serviceHistory: 'Full Service History',
    status: 'available'
  },
  {
    title: 'Audi A4 2.0 TFSI',
    description: 'Premium sedan with advanced technology',
    price: 32000,
    imagePath: 'https://m-qa.atcdn.co.uk/a/media/800x600/a805315414c144c49dcb6becda0ce740.jpg',
    year: 2021,
    brand: 'Audi',
    model: 'A4',
    fuelType: 'Petrol',
    autotraderId: 'audi_a4_001',
    category: 'cars',
    bodyType: 'Saloon',
    mileage: 18000,
    transmission: 'Automatic',
    doors: 4,
    seats: 5,
    co2Emissions: 135,
    engineSize: '2.0',
    power: '252',
    topSpeed: 155,
    acceleration: 6.5,
    mpg: 45,
    tax: 180,
    insurance: 'Group 25',
    drivetrain: 'FWD',
    cylinders: 4,
    colour: 'White',
    previousOwners: 0,
    serviceHistory: 'Full Service History',
    status: 'available'
  },
  {
    title: 'Mercedes-Benz C-Class C200',
    description: 'Luxury compact executive car',
    price: 35000,
    imagePath: 'https://m-qa.atcdn.co.uk/a/media/800x600/45946c9cef9e4f189d0114d81ef260d6.jpg',
    year: 2022,
    brand: 'Mercedes-Benz',
    model: 'C-Class',
    fuelType: 'Petrol',
    autotraderId: 'mercedes_c200_001',
    category: 'cars',
    bodyType: 'Saloon',
    mileage: 12000,
    transmission: 'Automatic',
    doors: 4,
    seats: 5,
    co2Emissions: 140,
    engineSize: '2.0',
    power: '204',
    topSpeed: 150,
    acceleration: 7.1,
    mpg: 42,
    tax: 200,
    insurance: 'Group 28',
    drivetrain: 'RWD',
    cylinders: 4,
    colour: 'Silver',
    previousOwners: 0,
    serviceHistory: 'Full Service History',
    status: 'available'
  },
  {
    title: 'Volkswagen Golf GTI',
    description: 'Hot hatch with sporty performance',
    price: 28000,
    imagePath: 'https://m-qa.atcdn.co.uk/a/media/800x600/c21c834da7524356a5adab9bc01785ef.jpg',
    year: 2021,
    brand: 'Volkswagen',
    model: 'Golf',
    fuelType: 'Petrol',
    autotraderId: 'vw_golf_gti_001',
    category: 'cars',
    bodyType: 'Hatchback',
    mileage: 22000,
    transmission: 'Manual',
    doors: 5,
    seats: 5,
    co2Emissions: 155,
    engineSize: '2.0',
    power: '245',
    topSpeed: 155,
    acceleration: 6.2,
    mpg: 38,
    tax: 220,
    insurance: 'Group 30',
    drivetrain: 'FWD',
    cylinders: 4,
    colour: 'Red',
    previousOwners: 1,
    serviceHistory: 'Full Service History',
    status: 'available'
  },
  {
    title: 'Ford Focus ST',
    description: 'Performance hatchback with sporty handling',
    price: 24000,
    imagePath: 'https://m-qa.atcdn.co.uk/a/media/800x600/8a82192e44b34f5a95743e47a4788e22.jpg',
    year: 2020,
    brand: 'Ford',
    model: 'Focus',
    fuelType: 'Petrol',
    autotraderId: 'ford_focus_st_001',
    category: 'cars',
    bodyType: 'Hatchback',
    mileage: 30000,
    transmission: 'Manual',
    doors: 5,
    seats: 5,
    co2Emissions: 165,
    engineSize: '2.3',
    power: '280',
    topSpeed: 155,
    acceleration: 5.7,
    mpg: 35,
    tax: 250,
    insurance: 'Group 32',
    drivetrain: 'FWD',
    cylinders: 4,
    colour: 'Blue',
    previousOwners: 2,
    serviceHistory: 'Full Service History',
    status: 'available'
  },
  {
    title: 'Toyota Prius Hybrid',
    description: 'Eco-friendly hybrid with excellent fuel economy',
    price: 22000,
    imagePath: 'https://m-qa.atcdn.co.uk/a/media/800x600/284526a256d04335a6a24e0e67ca7a0e.jpg',
    year: 2021,
    brand: 'Toyota',
    model: 'Prius',
    fuelType: 'Hybrid',
    autotraderId: 'toyota_prius_001',
    category: 'cars',
    bodyType: 'Hatchback',
    mileage: 15000,
    transmission: 'CVT',
    doors: 5,
    seats: 5,
    co2Emissions: 70,
    engineSize: '1.8',
    power: '122',
    topSpeed: 112,
    acceleration: 10.6,
    mpg: 65,
    tax: 0,
    insurance: 'Group 15',
    drivetrain: 'FWD',
    cylinders: 4,
    colour: 'White',
    previousOwners: 0,
    serviceHistory: 'Full Service History',
    status: 'available'
  },
  {
    title: 'Honda Civic Type R',
    description: 'High-performance hot hatch',
    price: 32000,
    imagePath: 'https://m-qa.atcdn.co.uk/a/media/800x600/099301534ba74ff7a20c8eff4408527a.jpg',
    year: 2022,
    brand: 'Honda',
    model: 'Civic',
    fuelType: 'Petrol',
    autotraderId: 'honda_civic_type_r_001',
    category: 'cars',
    bodyType: 'Hatchback',
    mileage: 8000,
    transmission: 'Manual',
    doors: 5,
    seats: 5,
    co2Emissions: 180,
    engineSize: '2.0',
    power: '320',
    topSpeed: 169,
    acceleration: 5.7,
    mpg: 32,
    tax: 280,
    insurance: 'Group 35',
    drivetrain: 'FWD',
    cylinders: 4,
    colour: 'Championship White',
    previousOwners: 0,
    serviceHistory: 'Full Service History',
    status: 'available'
  },
  {
    title: 'Nissan Leaf Electric',
    description: 'Pure electric vehicle with zero emissions',
    price: 25000,
    imagePath: 'https://m-qa.atcdn.co.uk/a/media/800x600/ff3f335d3da4450d9592e12c7ce6a306.jpg',
    year: 2021,
    brand: 'Nissan',
    model: 'Leaf',
    fuelType: 'Electric',
    autotraderId: 'nissan_leaf_001',
    category: 'cars',
    bodyType: 'Hatchback',
    mileage: 12000,
    transmission: 'Automatic',
    doors: 5,
    seats: 5,
    co2Emissions: 0,
    engineSize: 'Electric',
    power: '150',
    topSpeed: 90,
    acceleration: 7.9,
    mpg: 0,
    tax: 0,
    insurance: 'Group 20',
    drivetrain: 'FWD',
    cylinders: 0,
    colour: 'Blue',
    previousOwners: 0,
    serviceHistory: 'Full Service History',
    status: 'available'
  },
  {
    title: 'BMW X5 xDrive30d',
    description: 'Luxury SUV with excellent off-road capabilities',
    price: 45000,
    imagePath: 'https://m-qa.atcdn.co.uk/a/media/800x600/7fc20a8ffbff4bde82ac83744d1974ad.jpg',
    year: 2021,
    brand: 'BMW',
    model: 'X5',
    fuelType: 'Diesel',
    autotraderId: 'bmw_x5_001',
    category: 'cars',
    bodyType: 'SUV',
    mileage: 20000,
    transmission: 'Automatic',
    doors: 5,
    seats: 7,
    co2Emissions: 180,
    engineSize: '3.0',
    power: '265',
    topSpeed: 140,
    acceleration: 6.8,
    mpg: 42,
    tax: 250,
    insurance: 'Group 30',
    drivetrain: 'AWD',
    cylinders: 6,
    colour: 'Black',
    previousOwners: 1,
    serviceHistory: 'Full Service History',
    status: 'available'
  },
  {
    title: 'Audi Q7 3.0 TDI',
    description: 'Premium large SUV with seven seats',
    price: 50000,
    imagePath: 'https://m-qa.atcdn.co.uk/a/media/800x600/85e4b706a876407494670eb131c02ed3.jpg',
    year: 2022,
    brand: 'Audi',
    model: 'Q7',
    fuelType: 'Diesel',
    autotraderId: 'audi_q7_001',
    category: 'cars',
    bodyType: 'SUV',
    mileage: 15000,
    transmission: 'Automatic',
    doors: 5,
    seats: 7,
    co2Emissions: 200,
    engineSize: '3.0',
    power: '286',
    topSpeed: 145,
    acceleration: 6.5,
    mpg: 38,
    tax: 300,
    insurance: 'Group 35',
    drivetrain: 'AWD',
    cylinders: 6,
    colour: 'Grey',
    previousOwners: 0,
    serviceHistory: 'Full Service History',
    status: 'available'
  }
];

async function addVehicles() {
  try {
    console.log('Adding sample vehicles to database...');
    
    for (const vehicleData of sampleVehicles) {
      // Check if vehicle already exists
      const existingVehicle = await VehicleModel.findOne({ 
        autotraderId: vehicleData.autotraderId 
      });
      
      if (!existingVehicle) {
        const vehicle = new VehicleModel(vehicleData);
        await vehicle.save();
        console.log(`Added vehicle: ${vehicleData.title}`);
      } else {
        console.log(`Vehicle already exists: ${vehicleData.title}`);
      }
    }
    
    // Count total vehicles
    const totalVehicles = await VehicleModel.countDocuments({ status: 'available' });
    console.log(`Total vehicles in database: ${totalVehicles}`);
    
    console.log('Sample vehicles added successfully!');
  } catch (error) {
    console.error('Error adding vehicles:', error);
  } finally {
    mongoose.disconnect();
  }
}

addVehicles();
